# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Robo Ramble
email: khabcity@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my blog, and I'm going to post random notes here.
  Why "Robo Ramble"? Well, because I used to play a video game 
  with a similar name which stuck in my mind for some reason.
  Also, I expect articles posted here to be random and 
  not really well organized, hence "ramble".
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "96tm.github.io" # the base hostname & protocol for your site, e.g. http://example.com
show_excerpts: true # set to true to show excerpts on the homepage
permalink: /posts/:title/

# Build settings
markdown: kramdown
theme: texture
highlighter:      rouge
plugins:
  - jekyll-feed

texture:
  title: Robo Ramble
  tagline: Random notes
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  date_format: "%b %-d, %Y"
  
  navigation:
    - title: Blog
      url: "/"
    - title: About
      url: "/about"

  social_links:
    # twitter: thelehhman
    github:  96tm
    #linkedIn: in/thelehhman # format: locale/username

header_pages:
 - about.md    

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
